/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff/index'
import { Route as AuthenticatedRotaIndexRouteImport } from './routes/_authenticated/rota/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedProcurementIndexRouteImport } from './routes/_authenticated/procurement/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedLeaveIndexRouteImport } from './routes/_authenticated/leave/index'
import { Route as AuthenticatedContractsIndexRouteImport } from './routes/_authenticated/contracts/index'
import { Route as AuthenticatedAuditIndexRouteImport } from './routes/_authenticated/audit/index'
import { Route as AuthenticatedAppraisalsIndexRouteImport } from './routes/_authenticated/appraisals/index'
import { Route as AuthenticatedSettingsRolesRouteImport } from './routes/_authenticated/settings/roles'
import { Route as AuthenticatedSettingsLeaveTypesRouteImport } from './routes/_authenticated/settings/leave-types'
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated/settings/general'
import { Route as AuthenticatedSettingsDepartmentsRouteImport } from './routes/_authenticated/settings/departments'
import { Route as AuthenticatedComplianceTrainingRouteImport } from './routes/_authenticated/compliance/training'
import { Route as AuthenticatedCompliancePpeRouteImport } from './routes/_authenticated/compliance/ppe'
import { Route as AuthenticatedComplianceItemsRouteImport } from './routes/_authenticated/compliance/items'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRotaIndexRoute = AuthenticatedRotaIndexRouteImport.update({
  id: '/rota/',
  path: '/rota/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcurementIndexRoute =
  AuthenticatedProcurementIndexRouteImport.update({
    id: '/procurement/',
    path: '/procurement/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaveIndexRoute = AuthenticatedLeaveIndexRouteImport.update({
  id: '/leave/',
  path: '/leave/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContractsIndexRoute =
  AuthenticatedContractsIndexRouteImport.update({
    id: '/contracts/',
    path: '/contracts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditIndexRoute = AuthenticatedAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppraisalsIndexRoute =
  AuthenticatedAppraisalsIndexRouteImport.update({
    id: '/appraisals/',
    path: '/appraisals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRolesRoute =
  AuthenticatedSettingsRolesRouteImport.update({
    id: '/settings/roles',
    path: '/settings/roles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsLeaveTypesRoute =
  AuthenticatedSettingsLeaveTypesRouteImport.update({
    id: '/settings/leave-types',
    path: '/settings/leave-types',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsDepartmentsRoute =
  AuthenticatedSettingsDepartmentsRouteImport.update({
    id: '/settings/departments',
    path: '/settings/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComplianceTrainingRoute =
  AuthenticatedComplianceTrainingRouteImport.update({
    id: '/compliance/training',
    path: '/compliance/training',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompliancePpeRoute =
  AuthenticatedCompliancePpeRouteImport.update({
    id: '/compliance/ppe',
    path: '/compliance/ppe',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComplianceItemsRoute =
  AuthenticatedComplianceItemsRouteImport.update({
    id: '/compliance/items',
    path: '/compliance/items',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/compliance/items': typeof AuthenticatedComplianceItemsRoute
  '/compliance/ppe': typeof AuthenticatedCompliancePpeRoute
  '/compliance/training': typeof AuthenticatedComplianceTrainingRoute
  '/settings/departments': typeof AuthenticatedSettingsDepartmentsRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/leave-types': typeof AuthenticatedSettingsLeaveTypesRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/appraisals/': typeof AuthenticatedAppraisalsIndexRoute
  '/audit/': typeof AuthenticatedAuditIndexRoute
  '/contracts/': typeof AuthenticatedContractsIndexRoute
  '/leave/': typeof AuthenticatedLeaveIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/procurement/': typeof AuthenticatedProcurementIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/rota/': typeof AuthenticatedRotaIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/compliance/items': typeof AuthenticatedComplianceItemsRoute
  '/compliance/ppe': typeof AuthenticatedCompliancePpeRoute
  '/compliance/training': typeof AuthenticatedComplianceTrainingRoute
  '/settings/departments': typeof AuthenticatedSettingsDepartmentsRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/leave-types': typeof AuthenticatedSettingsLeaveTypesRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/appraisals': typeof AuthenticatedAppraisalsIndexRoute
  '/audit': typeof AuthenticatedAuditIndexRoute
  '/contracts': typeof AuthenticatedContractsIndexRoute
  '/leave': typeof AuthenticatedLeaveIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/procurement': typeof AuthenticatedProcurementIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/rota': typeof AuthenticatedRotaIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/compliance/items': typeof AuthenticatedComplianceItemsRoute
  '/_authenticated/compliance/ppe': typeof AuthenticatedCompliancePpeRoute
  '/_authenticated/compliance/training': typeof AuthenticatedComplianceTrainingRoute
  '/_authenticated/settings/departments': typeof AuthenticatedSettingsDepartmentsRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/settings/leave-types': typeof AuthenticatedSettingsLeaveTypesRoute
  '/_authenticated/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/_authenticated/appraisals/': typeof AuthenticatedAppraisalsIndexRoute
  '/_authenticated/audit/': typeof AuthenticatedAuditIndexRoute
  '/_authenticated/contracts/': typeof AuthenticatedContractsIndexRoute
  '/_authenticated/leave/': typeof AuthenticatedLeaveIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/procurement/': typeof AuthenticatedProcurementIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/rota/': typeof AuthenticatedRotaIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/compliance/items'
    | '/compliance/ppe'
    | '/compliance/training'
    | '/settings/departments'
    | '/settings/general'
    | '/settings/leave-types'
    | '/settings/roles'
    | '/appraisals/'
    | '/audit/'
    | '/contracts/'
    | '/leave/'
    | '/notifications/'
    | '/procurement/'
    | '/reports/'
    | '/rota/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/compliance/items'
    | '/compliance/ppe'
    | '/compliance/training'
    | '/settings/departments'
    | '/settings/general'
    | '/settings/leave-types'
    | '/settings/roles'
    | '/appraisals'
    | '/audit'
    | '/contracts'
    | '/leave'
    | '/notifications'
    | '/procurement'
    | '/reports'
    | '/rota'
    | '/staff'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/compliance/items'
    | '/_authenticated/compliance/ppe'
    | '/_authenticated/compliance/training'
    | '/_authenticated/settings/departments'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/leave-types'
    | '/_authenticated/settings/roles'
    | '/_authenticated/appraisals/'
    | '/_authenticated/audit/'
    | '/_authenticated/contracts/'
    | '/_authenticated/leave/'
    | '/_authenticated/notifications/'
    | '/_authenticated/procurement/'
    | '/_authenticated/reports/'
    | '/_authenticated/rota/'
    | '/_authenticated/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rota/': {
      id: '/_authenticated/rota/'
      path: '/rota'
      fullPath: '/rota/'
      preLoaderRoute: typeof AuthenticatedRotaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement/': {
      id: '/_authenticated/procurement/'
      path: '/procurement'
      fullPath: '/procurement/'
      preLoaderRoute: typeof AuthenticatedProcurementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave/': {
      id: '/_authenticated/leave/'
      path: '/leave'
      fullPath: '/leave/'
      preLoaderRoute: typeof AuthenticatedLeaveIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/': {
      id: '/_authenticated/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AuthenticatedContractsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit/': {
      id: '/_authenticated/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuthenticatedAuditIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appraisals/': {
      id: '/_authenticated/appraisals/'
      path: '/appraisals'
      fullPath: '/appraisals/'
      preLoaderRoute: typeof AuthenticatedAppraisalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/roles': {
      id: '/_authenticated/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AuthenticatedSettingsRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/leave-types': {
      id: '/_authenticated/settings/leave-types'
      path: '/settings/leave-types'
      fullPath: '/settings/leave-types'
      preLoaderRoute: typeof AuthenticatedSettingsLeaveTypesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/departments': {
      id: '/_authenticated/settings/departments'
      path: '/settings/departments'
      fullPath: '/settings/departments'
      preLoaderRoute: typeof AuthenticatedSettingsDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance/training': {
      id: '/_authenticated/compliance/training'
      path: '/compliance/training'
      fullPath: '/compliance/training'
      preLoaderRoute: typeof AuthenticatedComplianceTrainingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance/ppe': {
      id: '/_authenticated/compliance/ppe'
      path: '/compliance/ppe'
      fullPath: '/compliance/ppe'
      preLoaderRoute: typeof AuthenticatedCompliancePpeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance/items': {
      id: '/_authenticated/compliance/items'
      path: '/compliance/items'
      fullPath: '/compliance/items'
      preLoaderRoute: typeof AuthenticatedComplianceItemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedComplianceItemsRoute: typeof AuthenticatedComplianceItemsRoute
  AuthenticatedCompliancePpeRoute: typeof AuthenticatedCompliancePpeRoute
  AuthenticatedComplianceTrainingRoute: typeof AuthenticatedComplianceTrainingRoute
  AuthenticatedSettingsDepartmentsRoute: typeof AuthenticatedSettingsDepartmentsRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedSettingsLeaveTypesRoute: typeof AuthenticatedSettingsLeaveTypesRoute
  AuthenticatedSettingsRolesRoute: typeof AuthenticatedSettingsRolesRoute
  AuthenticatedAppraisalsIndexRoute: typeof AuthenticatedAppraisalsIndexRoute
  AuthenticatedAuditIndexRoute: typeof AuthenticatedAuditIndexRoute
  AuthenticatedContractsIndexRoute: typeof AuthenticatedContractsIndexRoute
  AuthenticatedLeaveIndexRoute: typeof AuthenticatedLeaveIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedProcurementIndexRoute: typeof AuthenticatedProcurementIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedRotaIndexRoute: typeof AuthenticatedRotaIndexRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedComplianceItemsRoute: AuthenticatedComplianceItemsRoute,
  AuthenticatedCompliancePpeRoute: AuthenticatedCompliancePpeRoute,
  AuthenticatedComplianceTrainingRoute: AuthenticatedComplianceTrainingRoute,
  AuthenticatedSettingsDepartmentsRoute: AuthenticatedSettingsDepartmentsRoute,
  AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
  AuthenticatedSettingsLeaveTypesRoute: AuthenticatedSettingsLeaveTypesRoute,
  AuthenticatedSettingsRolesRoute: AuthenticatedSettingsRolesRoute,
  AuthenticatedAppraisalsIndexRoute: AuthenticatedAppraisalsIndexRoute,
  AuthenticatedAuditIndexRoute: AuthenticatedAuditIndexRoute,
  AuthenticatedContractsIndexRoute: AuthenticatedContractsIndexRoute,
  AuthenticatedLeaveIndexRoute: AuthenticatedLeaveIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedProcurementIndexRoute: AuthenticatedProcurementIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedRotaIndexRoute: AuthenticatedRotaIndexRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
