/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedWorkIndexRouteImport } from './routes/_authenticated/work/index'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff/index'
import { Route as AuthenticatedServicesIndexRouteImport } from './routes/_authenticated/services/index'
import { Route as AuthenticatedRotaIndexRouteImport } from './routes/_authenticated/rota/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedProcurementIndexRouteImport } from './routes/_authenticated/procurement/index'
import { Route as AuthenticatedOpsReadinessIndexRouteImport } from './routes/_authenticated/ops-readiness/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedLeaveIndexRouteImport } from './routes/_authenticated/leave/index'
import { Route as AuthenticatedIncidentsIndexRouteImport } from './routes/_authenticated/incidents/index'
import { Route as AuthenticatedImportIndexRouteImport } from './routes/_authenticated/import/index'
import { Route as AuthenticatedCyclesIndexRouteImport } from './routes/_authenticated/cycles/index'
import { Route as AuthenticatedContractsIndexRouteImport } from './routes/_authenticated/contracts/index'
import { Route as AuthenticatedChangesIndexRouteImport } from './routes/_authenticated/changes/index'
import { Route as AuthenticatedAuditIndexRouteImport } from './routes/_authenticated/audit/index'
import { Route as AuthenticatedAppraisalsIndexRouteImport } from './routes/_authenticated/appraisals/index'
import { Route as AuthenticatedAppraisalsInboxRouteImport } from './routes/_authenticated/appraisals/inbox'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics/index'
import { Route as AuthenticatedAccessIndexRouteImport } from './routes/_authenticated/access/index'
import { Route as AuthenticatedWorkWorkloadRouteImport } from './routes/_authenticated/work/workload'
import { Route as AuthenticatedWorkNewRouteImport } from './routes/_authenticated/work/new'
import { Route as AuthenticatedWorkWorkItemIdRouteImport } from './routes/_authenticated/work/$workItemId'
import { Route as AuthenticatedStaffStaffIdRouteImport } from './routes/_authenticated/staff/$staffId'
import { Route as AuthenticatedSettingsRolesRouteImport } from './routes/_authenticated/settings/roles'
import { Route as AuthenticatedSettingsLeaveTypesRouteImport } from './routes/_authenticated/settings/leave-types'
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated/settings/general'
import { Route as AuthenticatedSettingsEscalationRouteImport } from './routes/_authenticated/settings/escalation'
import { Route as AuthenticatedSettingsDepartmentsRouteImport } from './routes/_authenticated/settings/departments'
import { Route as AuthenticatedSettingsDepartmentAssignmentsRouteImport } from './routes/_authenticated/settings/department-assignments'
import { Route as AuthenticatedSettingsAutomationRouteImport } from './routes/_authenticated/settings/automation'
import { Route as AuthenticatedRotaSwapsRouteImport } from './routes/_authenticated/rota/swaps'
import { Route as AuthenticatedRotaPlannerRouteImport } from './routes/_authenticated/rota/planner'
import { Route as AuthenticatedRotaHistoryRouteImport } from './routes/_authenticated/rota/history'
import { Route as AuthenticatedTimesheetsIndexRouteImport } from './routes/_authenticated/timesheets/index'
import { Route as AuthenticatedProcurementNewRouteImport } from './routes/_authenticated/procurement/new'
import { Route as AuthenticatedLeaveNewRouteImport } from './routes/_authenticated/leave/new'
import { Route as AuthenticatedLeaveCalendarRouteImport } from './routes/_authenticated/leave/calendar'
import { Route as AuthenticatedIncidentsNewRouteImport } from './routes/_authenticated/incidents/new'
import { Route as AuthenticatedIncidentsIncidentIdRouteImport } from './routes/_authenticated/incidents/$incidentId'
import { Route as AuthenticatedCyclesCycleIdRouteImport } from './routes/_authenticated/cycles/$cycleId'
import { Route as AuthenticatedComplianceTrainingRouteImport } from './routes/_authenticated/compliance/training'
import { Route as AuthenticatedCompliancePpeRouteImport } from './routes/_authenticated/compliance/ppe'
import { Route as AuthenticatedComplianceItemsRouteImport } from './routes/_authenticated/compliance/items'
import { Route as AuthenticatedHrAttendanceRouteImport } from './routes/_authenticated/hr/attendance'
import { Route as AuthenticatedHrCalloutsRouteImport } from './routes/_authenticated/hr/callouts'
import { Route as AuthenticatedHrPpeRouteImport } from './routes/_authenticated/hr/ppe'
import { Route as AuthenticatedChangesNewRouteImport } from './routes/_authenticated/changes/new'
import { Route as AuthenticatedChangesChangeIdRouteImport } from './routes/_authenticated/changes/$changeId'
import { Route as AuthenticatedAccessAccountIdRouteImport } from './routes/_authenticated/access/$accountId'
import { Route as AuthenticatedRotaWarningsIndexRouteImport } from './routes/_authenticated/rota/warnings/index'
import { Route as AuthenticatedRotaFairnessIndexRouteImport } from './routes/_authenticated/rota/fairness/index'
import { Route as AuthenticatedRotaCalendarIndexRouteImport } from './routes/_authenticated/rota/calendar/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkIndexRoute = AuthenticatedWorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicesIndexRoute =
  AuthenticatedServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRotaIndexRoute = AuthenticatedRotaIndexRouteImport.update({
  id: '/rota/',
  path: '/rota/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcurementIndexRoute =
  AuthenticatedProcurementIndexRouteImport.update({
    id: '/procurement/',
    path: '/procurement/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpsReadinessIndexRoute =
  AuthenticatedOpsReadinessIndexRouteImport.update({
    id: '/ops-readiness/',
    path: '/ops-readiness/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaveIndexRoute = AuthenticatedLeaveIndexRouteImport.update({
  id: '/leave/',
  path: '/leave/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIncidentsIndexRoute =
  AuthenticatedIncidentsIndexRouteImport.update({
    id: '/incidents/',
    path: '/incidents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportIndexRoute =
  AuthenticatedImportIndexRouteImport.update({
    id: '/import/',
    path: '/import/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCyclesIndexRoute =
  AuthenticatedCyclesIndexRouteImport.update({
    id: '/cycles/',
    path: '/cycles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsIndexRoute =
  AuthenticatedContractsIndexRouteImport.update({
    id: '/contracts/',
    path: '/contracts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChangesIndexRoute =
  AuthenticatedChangesIndexRouteImport.update({
    id: '/changes/',
    path: '/changes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditIndexRoute = AuthenticatedAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppraisalsIndexRoute =
  AuthenticatedAppraisalsIndexRouteImport.update({
    id: '/appraisals/',
    path: '/appraisals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppraisalsInboxRoute =
  AuthenticatedAppraisalsInboxRouteImport.update({
    id: '/appraisals/inbox',
    path: '/appraisals/inbox',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccessIndexRoute =
  AuthenticatedAccessIndexRouteImport.update({
    id: '/access/',
    path: '/access/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkWorkloadRoute =
  AuthenticatedWorkWorkloadRouteImport.update({
    id: '/work/workload',
    path: '/work/workload',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkNewRoute = AuthenticatedWorkNewRouteImport.update({
  id: '/work/new',
  path: '/work/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkWorkItemIdRoute =
  AuthenticatedWorkWorkItemIdRouteImport.update({
    id: '/work/$workItemId',
    path: '/work/$workItemId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffStaffIdRoute =
  AuthenticatedStaffStaffIdRouteImport.update({
    id: '/staff/$staffId',
    path: '/staff/$staffId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRolesRoute =
  AuthenticatedSettingsRolesRouteImport.update({
    id: '/settings/roles',
    path: '/settings/roles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsLeaveTypesRoute =
  AuthenticatedSettingsLeaveTypesRouteImport.update({
    id: '/settings/leave-types',
    path: '/settings/leave-types',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsEscalationRoute =
  AuthenticatedSettingsEscalationRouteImport.update({
    id: '/settings/escalation',
    path: '/settings/escalation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsDepartmentsRoute =
  AuthenticatedSettingsDepartmentsRouteImport.update({
    id: '/settings/departments',
    path: '/settings/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsDepartmentAssignmentsRoute =
  AuthenticatedSettingsDepartmentAssignmentsRouteImport.update({
    id: '/settings/department-assignments',
    path: '/settings/department-assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAutomationRoute =
  AuthenticatedSettingsAutomationRouteImport.update({
    id: '/settings/automation',
    path: '/settings/automation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRotaSwapsRoute = AuthenticatedRotaSwapsRouteImport.update({
  id: '/rota/swaps',
  path: '/rota/swaps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRotaPlannerRoute =
  AuthenticatedRotaPlannerRouteImport.update({
    id: '/rota/planner',
    path: '/rota/planner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRotaHistoryRoute =
  AuthenticatedRotaHistoryRouteImport.update({
    id: '/rota/history',
    path: '/rota/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcurementNewRoute =
  AuthenticatedProcurementNewRouteImport.update({
    id: '/procurement/new',
    path: '/procurement/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaveNewRoute = AuthenticatedLeaveNewRouteImport.update({
  id: '/leave/new',
  path: '/leave/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaveCalendarRoute =
  AuthenticatedLeaveCalendarRouteImport.update({
    id: '/leave/calendar',
    path: '/leave/calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIncidentsNewRoute =
  AuthenticatedIncidentsNewRouteImport.update({
    id: '/incidents/new',
    path: '/incidents/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIncidentsIncidentIdRoute =
  AuthenticatedIncidentsIncidentIdRouteImport.update({
    id: '/incidents/$incidentId',
    path: '/incidents/$incidentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCyclesCycleIdRoute =
  AuthenticatedCyclesCycleIdRouteImport.update({
    id: '/cycles/$cycleId',
    path: '/cycles/$cycleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComplianceTrainingRoute =
  AuthenticatedComplianceTrainingRouteImport.update({
    id: '/compliance/training',
    path: '/compliance/training',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompliancePpeRoute =
  AuthenticatedCompliancePpeRouteImport.update({
    id: '/compliance/ppe',
    path: '/compliance/ppe',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComplianceItemsRoute =
  AuthenticatedComplianceItemsRouteImport.update({
    id: '/compliance/items',
    path: '/compliance/items',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrAttendanceRoute =
  AuthenticatedHrAttendanceRouteImport.update({
    id: '/hr/attendance',
    path: '/hr/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrCalloutsRoute =
  AuthenticatedHrCalloutsRouteImport.update({
    id: '/hr/callouts',
    path: '/hr/callouts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrPpeRoute = AuthenticatedHrPpeRouteImport.update({
  id: '/hr/ppe',
  path: '/hr/ppe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangesNewRoute = AuthenticatedChangesNewRouteImport.update({
  id: '/changes/new',
  path: '/changes/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangesChangeIdRoute =
  AuthenticatedChangesChangeIdRouteImport.update({
    id: '/changes/$changeId',
    path: '/changes/$changeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccessAccountIdRoute =
  AuthenticatedAccessAccountIdRouteImport.update({
    id: '/access/$accountId',
    path: '/access/$accountId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRotaWarningsIndexRoute =
  AuthenticatedRotaWarningsIndexRouteImport.update({
    id: '/rota/warnings/',
    path: '/rota/warnings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRotaFairnessIndexRoute =
  AuthenticatedRotaFairnessIndexRouteImport.update({
    id: '/rota/fairness/',
    path: '/rota/fairness/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRotaCalendarIndexRoute =
  AuthenticatedRotaCalendarIndexRouteImport.update({
    id: '/rota/calendar/',
    path: '/rota/calendar/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimesheetsIndexRoute =
  AuthenticatedTimesheetsIndexRouteImport.update({
    id: '/timesheets/',
    path: '/timesheets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/access/$accountId': typeof AuthenticatedAccessAccountIdRoute
  '/changes/$changeId': typeof AuthenticatedChangesChangeIdRoute
  '/changes/new': typeof AuthenticatedChangesNewRoute
  '/compliance/items': typeof AuthenticatedComplianceItemsRoute
  '/compliance/ppe': typeof AuthenticatedCompliancePpeRoute
  '/compliance/training': typeof AuthenticatedComplianceTrainingRoute
  '/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/hr/callouts': typeof AuthenticatedHrCalloutsRoute
  '/hr/ppe': typeof AuthenticatedHrPpeRoute
  '/cycles/$cycleId': typeof AuthenticatedCyclesCycleIdRoute
  '/incidents/$incidentId': typeof AuthenticatedIncidentsIncidentIdRoute
  '/incidents/new': typeof AuthenticatedIncidentsNewRoute
  '/leave/calendar': typeof AuthenticatedLeaveCalendarRoute
  '/leave/new': typeof AuthenticatedLeaveNewRoute
  '/procurement/new': typeof AuthenticatedProcurementNewRoute
  '/rota/history': typeof AuthenticatedRotaHistoryRoute
  '/rota/planner': typeof AuthenticatedRotaPlannerRoute
  '/rota/swaps': typeof AuthenticatedRotaSwapsRoute
  '/settings/automation': typeof AuthenticatedSettingsAutomationRoute
  '/settings/department-assignments': typeof AuthenticatedSettingsDepartmentAssignmentsRoute
  '/settings/departments': typeof AuthenticatedSettingsDepartmentsRoute
  '/settings/escalation': typeof AuthenticatedSettingsEscalationRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/leave-types': typeof AuthenticatedSettingsLeaveTypesRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
  '/work/$workItemId': typeof AuthenticatedWorkWorkItemIdRoute
  '/work/new': typeof AuthenticatedWorkNewRoute
  '/work/workload': typeof AuthenticatedWorkWorkloadRoute
  '/access/': typeof AuthenticatedAccessIndexRoute
  '/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/appraisals/': typeof AuthenticatedAppraisalsIndexRoute
  '/appraisals/inbox': typeof AuthenticatedAppraisalsInboxRoute
  '/audit/': typeof AuthenticatedAuditIndexRoute
  '/changes/': typeof AuthenticatedChangesIndexRoute
  '/contracts/': typeof AuthenticatedContractsIndexRoute
  '/cycles/': typeof AuthenticatedCyclesIndexRoute
  '/import/': typeof AuthenticatedImportIndexRoute
  '/incidents/': typeof AuthenticatedIncidentsIndexRoute
  '/leave/': typeof AuthenticatedLeaveIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/ops-readiness/': typeof AuthenticatedOpsReadinessIndexRoute
  '/procurement/': typeof AuthenticatedProcurementIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/rota/': typeof AuthenticatedRotaIndexRoute
  '/services/': typeof AuthenticatedServicesIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/work/': typeof AuthenticatedWorkIndexRoute
  '/rota/calendar/': typeof AuthenticatedRotaCalendarIndexRoute
  '/rota/fairness/': typeof AuthenticatedRotaFairnessIndexRoute
  '/rota/warnings/': typeof AuthenticatedRotaWarningsIndexRoute
  '/timesheets/': typeof AuthenticatedTimesheetsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/access/$accountId': typeof AuthenticatedAccessAccountIdRoute
  '/changes/$changeId': typeof AuthenticatedChangesChangeIdRoute
  '/changes/new': typeof AuthenticatedChangesNewRoute
  '/compliance/items': typeof AuthenticatedComplianceItemsRoute
  '/compliance/ppe': typeof AuthenticatedCompliancePpeRoute
  '/compliance/training': typeof AuthenticatedComplianceTrainingRoute
  '/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/hr/callouts': typeof AuthenticatedHrCalloutsRoute
  '/hr/ppe': typeof AuthenticatedHrPpeRoute
  '/cycles/$cycleId': typeof AuthenticatedCyclesCycleIdRoute
  '/incidents/$incidentId': typeof AuthenticatedIncidentsIncidentIdRoute
  '/incidents/new': typeof AuthenticatedIncidentsNewRoute
  '/leave/calendar': typeof AuthenticatedLeaveCalendarRoute
  '/leave/new': typeof AuthenticatedLeaveNewRoute
  '/procurement/new': typeof AuthenticatedProcurementNewRoute
  '/rota/history': typeof AuthenticatedRotaHistoryRoute
  '/rota/planner': typeof AuthenticatedRotaPlannerRoute
  '/rota/swaps': typeof AuthenticatedRotaSwapsRoute
  '/settings/automation': typeof AuthenticatedSettingsAutomationRoute
  '/settings/department-assignments': typeof AuthenticatedSettingsDepartmentAssignmentsRoute
  '/settings/departments': typeof AuthenticatedSettingsDepartmentsRoute
  '/settings/escalation': typeof AuthenticatedSettingsEscalationRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/leave-types': typeof AuthenticatedSettingsLeaveTypesRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
  '/work/$workItemId': typeof AuthenticatedWorkWorkItemIdRoute
  '/work/new': typeof AuthenticatedWorkNewRoute
  '/work/workload': typeof AuthenticatedWorkWorkloadRoute
  '/access': typeof AuthenticatedAccessIndexRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/appraisals': typeof AuthenticatedAppraisalsIndexRoute
  '/appraisals/inbox': typeof AuthenticatedAppraisalsInboxRoute
  '/audit': typeof AuthenticatedAuditIndexRoute
  '/changes': typeof AuthenticatedChangesIndexRoute
  '/contracts': typeof AuthenticatedContractsIndexRoute
  '/cycles': typeof AuthenticatedCyclesIndexRoute
  '/import': typeof AuthenticatedImportIndexRoute
  '/incidents': typeof AuthenticatedIncidentsIndexRoute
  '/leave': typeof AuthenticatedLeaveIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/ops-readiness': typeof AuthenticatedOpsReadinessIndexRoute
  '/procurement': typeof AuthenticatedProcurementIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/rota': typeof AuthenticatedRotaIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/work': typeof AuthenticatedWorkIndexRoute
  '/rota/calendar': typeof AuthenticatedRotaCalendarIndexRoute
  '/rota/fairness': typeof AuthenticatedRotaFairnessIndexRoute
  '/rota/warnings': typeof AuthenticatedRotaWarningsIndexRoute
  '/timesheets': typeof AuthenticatedTimesheetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/access/$accountId': typeof AuthenticatedAccessAccountIdRoute
  '/_authenticated/changes/$changeId': typeof AuthenticatedChangesChangeIdRoute
  '/_authenticated/changes/new': typeof AuthenticatedChangesNewRoute
  '/_authenticated/compliance/items': typeof AuthenticatedComplianceItemsRoute
  '/_authenticated/compliance/ppe': typeof AuthenticatedCompliancePpeRoute
  '/_authenticated/compliance/training': typeof AuthenticatedComplianceTrainingRoute
  '/_authenticated/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/_authenticated/hr/callouts': typeof AuthenticatedHrCalloutsRoute
  '/_authenticated/hr/ppe': typeof AuthenticatedHrPpeRoute
  '/_authenticated/cycles/$cycleId': typeof AuthenticatedCyclesCycleIdRoute
  '/_authenticated/incidents/$incidentId': typeof AuthenticatedIncidentsIncidentIdRoute
  '/_authenticated/incidents/new': typeof AuthenticatedIncidentsNewRoute
  '/_authenticated/leave/calendar': typeof AuthenticatedLeaveCalendarRoute
  '/_authenticated/leave/new': typeof AuthenticatedLeaveNewRoute
  '/_authenticated/procurement/new': typeof AuthenticatedProcurementNewRoute
  '/_authenticated/rota/history': typeof AuthenticatedRotaHistoryRoute
  '/_authenticated/rota/planner': typeof AuthenticatedRotaPlannerRoute
  '/_authenticated/rota/swaps': typeof AuthenticatedRotaSwapsRoute
  '/_authenticated/settings/automation': typeof AuthenticatedSettingsAutomationRoute
  '/_authenticated/settings/department-assignments': typeof AuthenticatedSettingsDepartmentAssignmentsRoute
  '/_authenticated/settings/departments': typeof AuthenticatedSettingsDepartmentsRoute
  '/_authenticated/settings/escalation': typeof AuthenticatedSettingsEscalationRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/settings/leave-types': typeof AuthenticatedSettingsLeaveTypesRoute
  '/_authenticated/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/_authenticated/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
  '/_authenticated/work/$workItemId': typeof AuthenticatedWorkWorkItemIdRoute
  '/_authenticated/work/new': typeof AuthenticatedWorkNewRoute
  '/_authenticated/work/workload': typeof AuthenticatedWorkWorkloadRoute
  '/_authenticated/access/': typeof AuthenticatedAccessIndexRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/appraisals/': typeof AuthenticatedAppraisalsIndexRoute
  '/_authenticated/appraisals/inbox': typeof AuthenticatedAppraisalsInboxRoute
  '/_authenticated/audit/': typeof AuthenticatedAuditIndexRoute
  '/_authenticated/changes/': typeof AuthenticatedChangesIndexRoute
  '/_authenticated/contracts/': typeof AuthenticatedContractsIndexRoute
  '/_authenticated/cycles/': typeof AuthenticatedCyclesIndexRoute
  '/_authenticated/import/': typeof AuthenticatedImportIndexRoute
  '/_authenticated/incidents/': typeof AuthenticatedIncidentsIndexRoute
  '/_authenticated/leave/': typeof AuthenticatedLeaveIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/ops-readiness/': typeof AuthenticatedOpsReadinessIndexRoute
  '/_authenticated/procurement/': typeof AuthenticatedProcurementIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/rota/': typeof AuthenticatedRotaIndexRoute
  '/_authenticated/services/': typeof AuthenticatedServicesIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/_authenticated/work/': typeof AuthenticatedWorkIndexRoute
  '/_authenticated/rota/calendar/': typeof AuthenticatedRotaCalendarIndexRoute
  '/_authenticated/rota/fairness/': typeof AuthenticatedRotaFairnessIndexRoute
  '/_authenticated/rota/warnings/': typeof AuthenticatedRotaWarningsIndexRoute
  '/_authenticated/timesheets/': typeof AuthenticatedTimesheetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/access/$accountId'
    | '/changes/$changeId'
    | '/changes/new'
    | '/compliance/items'
    | '/compliance/ppe'
    | '/compliance/training'
    | '/hr/attendance'
    | '/hr/callouts'
    | '/hr/ppe'
    | '/cycles/$cycleId'
    | '/incidents/$incidentId'
    | '/incidents/new'
    | '/leave/calendar'
    | '/leave/new'
    | '/procurement/new'
    | '/rota/history'
    | '/rota/planner'
    | '/rota/swaps'
    | '/settings/automation'
    | '/settings/department-assignments'
    | '/settings/departments'
    | '/settings/escalation'
    | '/settings/general'
    | '/settings/leave-types'
    | '/settings/roles'
    | '/staff/$staffId'
    | '/work/$workItemId'
    | '/work/new'
    | '/work/workload'
    | '/access/'
    | '/analytics/'
    | '/appraisals/'
    | '/audit/'
    | '/changes/'
    | '/contracts/'
    | '/cycles/'
    | '/import/'
    | '/incidents/'
    | '/leave/'
    | '/notifications/'
    | '/ops-readiness/'
    | '/procurement/'
    | '/reports/'
    | '/rota/'
    | '/services/'
    | '/staff/'
    | '/work/'
    | '/rota/calendar/'
    | '/rota/fairness/'
    | '/rota/warnings/'
    | '/timesheets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/profile'
    | '/'
    | '/access/$accountId'
    | '/changes/$changeId'
    | '/changes/new'
    | '/compliance/items'
    | '/compliance/ppe'
    | '/compliance/training'
    | '/hr/attendance'
    | '/hr/callouts'
    | '/hr/ppe'
    | '/cycles/$cycleId'
    | '/incidents/$incidentId'
    | '/incidents/new'
    | '/leave/calendar'
    | '/leave/new'
    | '/procurement/new'
    | '/rota/history'
    | '/rota/planner'
    | '/rota/swaps'
    | '/settings/automation'
    | '/settings/department-assignments'
    | '/settings/departments'
    | '/settings/escalation'
    | '/settings/general'
    | '/settings/leave-types'
    | '/settings/roles'
    | '/staff/$staffId'
    | '/work/$workItemId'
    | '/work/new'
    | '/work/workload'
    | '/access'
    | '/analytics'
    | '/appraisals'
    | '/audit'
    | '/changes'
    | '/contracts'
    | '/cycles'
    | '/import'
    | '/incidents'
    | '/leave'
    | '/notifications'
    | '/ops-readiness'
    | '/procurement'
    | '/reports'
    | '/rota'
    | '/services'
    | '/staff'
    | '/work'
    | '/rota/calendar'
    | '/rota/fairness'
    | '/rota/warnings'
    | '/timesheets'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/_authenticated/access/$accountId'
    | '/_authenticated/changes/$changeId'
    | '/_authenticated/changes/new'
    | '/_authenticated/compliance/items'
    | '/_authenticated/compliance/ppe'
    | '/_authenticated/compliance/training'
    | '/_authenticated/hr/attendance'
    | '/_authenticated/hr/callouts'
    | '/_authenticated/hr/ppe'
    | '/_authenticated/cycles/$cycleId'
    | '/_authenticated/incidents/$incidentId'
    | '/_authenticated/incidents/new'
    | '/_authenticated/leave/calendar'
    | '/_authenticated/leave/new'
    | '/_authenticated/procurement/new'
    | '/_authenticated/rota/history'
    | '/_authenticated/rota/planner'
    | '/_authenticated/rota/swaps'
    | '/_authenticated/timesheets/'
    | '/_authenticated/settings/automation'
    | '/_authenticated/settings/department-assignments'
    | '/_authenticated/settings/departments'
    | '/_authenticated/settings/escalation'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/leave-types'
    | '/_authenticated/settings/roles'
    | '/_authenticated/staff/$staffId'
    | '/_authenticated/work/$workItemId'
    | '/_authenticated/work/new'
    | '/_authenticated/work/workload'
    | '/_authenticated/access/'
    | '/_authenticated/analytics/'
    | '/_authenticated/appraisals/'
    | '/_authenticated/audit/'
    | '/_authenticated/changes/'
    | '/_authenticated/contracts/'
    | '/_authenticated/cycles/'
    | '/_authenticated/import/'
    | '/_authenticated/incidents/'
    | '/_authenticated/leave/'
    | '/_authenticated/notifications/'
    | '/_authenticated/ops-readiness/'
    | '/_authenticated/procurement/'
    | '/_authenticated/reports/'
    | '/_authenticated/rota/'
    | '/_authenticated/services/'
    | '/_authenticated/staff/'
    | '/_authenticated/work/'
    | '/_authenticated/rota/calendar/'
    | '/_authenticated/rota/fairness/'
    | '/_authenticated/rota/warnings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work/': {
      id: '/_authenticated/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof AuthenticatedWorkIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services/': {
      id: '/_authenticated/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AuthenticatedServicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rota/': {
      id: '/_authenticated/rota/'
      path: '/rota'
      fullPath: '/rota/'
      preLoaderRoute: typeof AuthenticatedRotaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement/': {
      id: '/_authenticated/procurement/'
      path: '/procurement'
      fullPath: '/procurement/'
      preLoaderRoute: typeof AuthenticatedProcurementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ops-readiness/': {
      id: '/_authenticated/ops-readiness/'
      path: '/ops-readiness'
      fullPath: '/ops-readiness/'
      preLoaderRoute: typeof AuthenticatedOpsReadinessIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave/': {
      id: '/_authenticated/leave/'
      path: '/leave'
      fullPath: '/leave/'
      preLoaderRoute: typeof AuthenticatedLeaveIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidents/': {
      id: '/_authenticated/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof AuthenticatedIncidentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import/': {
      id: '/_authenticated/import/'
      path: '/import'
      fullPath: '/import/'
      preLoaderRoute: typeof AuthenticatedImportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cycles/': {
      id: '/_authenticated/cycles/'
      path: '/cycles'
      fullPath: '/cycles/'
      preLoaderRoute: typeof AuthenticatedCyclesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/': {
      id: '/_authenticated/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AuthenticatedContractsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/changes/': {
      id: '/_authenticated/changes/'
      path: '/changes'
      fullPath: '/changes/'
      preLoaderRoute: typeof AuthenticatedChangesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit/': {
      id: '/_authenticated/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuthenticatedAuditIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appraisals/': {
      id: '/_authenticated/appraisals/'
      path: '/appraisals'
      fullPath: '/appraisals/'
      preLoaderRoute: typeof AuthenticatedAppraisalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appraisals/inbox': {
      id: '/_authenticated/appraisals/inbox'
      path: '/appraisals/inbox'
      fullPath: '/appraisals/inbox'
      preLoaderRoute: typeof AuthenticatedAppraisalsInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/access/': {
      id: '/_authenticated/access/'
      path: '/access'
      fullPath: '/access/'
      preLoaderRoute: typeof AuthenticatedAccessIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work/workload': {
      id: '/_authenticated/work/workload'
      path: '/work/workload'
      fullPath: '/work/workload'
      preLoaderRoute: typeof AuthenticatedWorkWorkloadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work/new': {
      id: '/_authenticated/work/new'
      path: '/work/new'
      fullPath: '/work/new'
      preLoaderRoute: typeof AuthenticatedWorkNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work/$workItemId': {
      id: '/_authenticated/work/$workItemId'
      path: '/work/$workItemId'
      fullPath: '/work/$workItemId'
      preLoaderRoute: typeof AuthenticatedWorkWorkItemIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/$staffId': {
      id: '/_authenticated/staff/$staffId'
      path: '/staff/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof AuthenticatedStaffStaffIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/roles': {
      id: '/_authenticated/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AuthenticatedSettingsRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/leave-types': {
      id: '/_authenticated/settings/leave-types'
      path: '/settings/leave-types'
      fullPath: '/settings/leave-types'
      preLoaderRoute: typeof AuthenticatedSettingsLeaveTypesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/escalation': {
      id: '/_authenticated/settings/escalation'
      path: '/settings/escalation'
      fullPath: '/settings/escalation'
      preLoaderRoute: typeof AuthenticatedSettingsEscalationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/departments': {
      id: '/_authenticated/settings/departments'
      path: '/settings/departments'
      fullPath: '/settings/departments'
      preLoaderRoute: typeof AuthenticatedSettingsDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/automation': {
      id: '/_authenticated/settings/automation'
      path: '/settings/automation'
      fullPath: '/settings/automation'
      preLoaderRoute: typeof AuthenticatedSettingsAutomationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/department-assignments': {
      id: '/_authenticated/settings/department-assignments'
      path: '/settings/department-assignments'
      fullPath: '/settings/department-assignments'
      preLoaderRoute: typeof AuthenticatedSettingsDepartmentAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rota/swaps': {
      id: '/_authenticated/rota/swaps'
      path: '/rota/swaps'
      fullPath: '/rota/swaps'
      preLoaderRoute: typeof AuthenticatedRotaSwapsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rota/planner': {
      id: '/_authenticated/rota/planner'
      path: '/rota/planner'
      fullPath: '/rota/planner'
      preLoaderRoute: typeof AuthenticatedRotaPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rota/history': {
      id: '/_authenticated/rota/history'
      path: '/rota/history'
      fullPath: '/rota/history'
      preLoaderRoute: typeof AuthenticatedRotaHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement/new': {
      id: '/_authenticated/procurement/new'
      path: '/procurement/new'
      fullPath: '/procurement/new'
      preLoaderRoute: typeof AuthenticatedProcurementNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave/new': {
      id: '/_authenticated/leave/new'
      path: '/leave/new'
      fullPath: '/leave/new'
      preLoaderRoute: typeof AuthenticatedLeaveNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave/calendar': {
      id: '/_authenticated/leave/calendar'
      path: '/leave/calendar'
      fullPath: '/leave/calendar'
      preLoaderRoute: typeof AuthenticatedLeaveCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidents/new': {
      id: '/_authenticated/incidents/new'
      path: '/incidents/new'
      fullPath: '/incidents/new'
      preLoaderRoute: typeof AuthenticatedIncidentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidents/$incidentId': {
      id: '/_authenticated/incidents/$incidentId'
      path: '/incidents/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof AuthenticatedIncidentsIncidentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cycles/$cycleId': {
      id: '/_authenticated/cycles/$cycleId'
      path: '/cycles/$cycleId'
      fullPath: '/cycles/$cycleId'
      preLoaderRoute: typeof AuthenticatedCyclesCycleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance/training': {
      id: '/_authenticated/compliance/training'
      path: '/compliance/training'
      fullPath: '/compliance/training'
      preLoaderRoute: typeof AuthenticatedComplianceTrainingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance/ppe': {
      id: '/_authenticated/compliance/ppe'
      path: '/compliance/ppe'
      fullPath: '/compliance/ppe'
      preLoaderRoute: typeof AuthenticatedCompliancePpeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance/items': {
      id: '/_authenticated/compliance/items'
      path: '/compliance/items'
      fullPath: '/compliance/items'
      preLoaderRoute: typeof AuthenticatedComplianceItemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/attendance': {
      id: '/_authenticated/hr/attendance'
      path: '/hr/attendance'
      fullPath: '/hr/attendance'
      preLoaderRoute: typeof AuthenticatedHrAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/callouts': {
      id: '/_authenticated/hr/callouts'
      path: '/hr/callouts'
      fullPath: '/hr/callouts'
      preLoaderRoute: typeof AuthenticatedHrCalloutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/ppe': {
      id: '/_authenticated/hr/ppe'
      path: '/hr/ppe'
      fullPath: '/hr/ppe'
      preLoaderRoute: typeof AuthenticatedHrPpeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/changes/new': {
      id: '/_authenticated/changes/new'
      path: '/changes/new'
      fullPath: '/changes/new'
      preLoaderRoute: typeof AuthenticatedChangesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/changes/$changeId': {
      id: '/_authenticated/changes/$changeId'
      path: '/changes/$changeId'
      fullPath: '/changes/$changeId'
      preLoaderRoute: typeof AuthenticatedChangesChangeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/access/$accountId': {
      id: '/_authenticated/access/$accountId'
      path: '/access/$accountId'
      fullPath: '/access/$accountId'
      preLoaderRoute: typeof AuthenticatedAccessAccountIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rota/warnings/': {
      id: '/_authenticated/rota/warnings/'
      path: '/rota/warnings'
      fullPath: '/rota/warnings/'
      preLoaderRoute: typeof AuthenticatedRotaWarningsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timesheets/': {
      id: '/_authenticated/timesheets/'
      path: '/timesheets'
      fullPath: '/timesheets/'
      preLoaderRoute: typeof AuthenticatedTimesheetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rota/fairness/': {
      id: '/_authenticated/rota/fairness/'
      path: '/rota/fairness'
      fullPath: '/rota/fairness/'
      preLoaderRoute: typeof AuthenticatedRotaFairnessIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rota/calendar/': {
      id: '/_authenticated/rota/calendar/'
      path: '/rota/calendar'
      fullPath: '/rota/calendar/'
      preLoaderRoute: typeof AuthenticatedRotaCalendarIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAccessAccountIdRoute: typeof AuthenticatedAccessAccountIdRoute
  AuthenticatedChangesChangeIdRoute: typeof AuthenticatedChangesChangeIdRoute
  AuthenticatedChangesNewRoute: typeof AuthenticatedChangesNewRoute
  AuthenticatedComplianceItemsRoute: typeof AuthenticatedComplianceItemsRoute
  AuthenticatedCompliancePpeRoute: typeof AuthenticatedCompliancePpeRoute
  AuthenticatedComplianceTrainingRoute: typeof AuthenticatedComplianceTrainingRoute
  AuthenticatedHrAttendanceRoute: typeof AuthenticatedHrAttendanceRoute
  AuthenticatedHrCalloutsRoute: typeof AuthenticatedHrCalloutsRoute
  AuthenticatedHrPpeRoute: typeof AuthenticatedHrPpeRoute
  AuthenticatedCyclesCycleIdRoute: typeof AuthenticatedCyclesCycleIdRoute
  AuthenticatedIncidentsIncidentIdRoute: typeof AuthenticatedIncidentsIncidentIdRoute
  AuthenticatedIncidentsNewRoute: typeof AuthenticatedIncidentsNewRoute
  AuthenticatedLeaveCalendarRoute: typeof AuthenticatedLeaveCalendarRoute
  AuthenticatedLeaveNewRoute: typeof AuthenticatedLeaveNewRoute
  AuthenticatedProcurementNewRoute: typeof AuthenticatedProcurementNewRoute
  AuthenticatedRotaHistoryRoute: typeof AuthenticatedRotaHistoryRoute
  AuthenticatedRotaPlannerRoute: typeof AuthenticatedRotaPlannerRoute
  AuthenticatedRotaSwapsRoute: typeof AuthenticatedRotaSwapsRoute
  AuthenticatedSettingsAutomationRoute: typeof AuthenticatedSettingsAutomationRoute
  AuthenticatedSettingsDepartmentsRoute: typeof AuthenticatedSettingsDepartmentsRoute
  AuthenticatedSettingsEscalationRoute: typeof AuthenticatedSettingsEscalationRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedSettingsLeaveTypesRoute: typeof AuthenticatedSettingsLeaveTypesRoute
  AuthenticatedSettingsRolesRoute: typeof AuthenticatedSettingsRolesRoute
  AuthenticatedStaffStaffIdRoute: typeof AuthenticatedStaffStaffIdRoute
  AuthenticatedWorkWorkItemIdRoute: typeof AuthenticatedWorkWorkItemIdRoute
  AuthenticatedWorkNewRoute: typeof AuthenticatedWorkNewRoute
  AuthenticatedWorkWorkloadRoute: typeof AuthenticatedWorkWorkloadRoute
  AuthenticatedAccessIndexRoute: typeof AuthenticatedAccessIndexRoute
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
  AuthenticatedAppraisalsIndexRoute: typeof AuthenticatedAppraisalsIndexRoute
  AuthenticatedAppraisalsInboxRoute: typeof AuthenticatedAppraisalsInboxRoute
  AuthenticatedAuditIndexRoute: typeof AuthenticatedAuditIndexRoute
  AuthenticatedChangesIndexRoute: typeof AuthenticatedChangesIndexRoute
  AuthenticatedContractsIndexRoute: typeof AuthenticatedContractsIndexRoute
  AuthenticatedCyclesIndexRoute: typeof AuthenticatedCyclesIndexRoute
  AuthenticatedImportIndexRoute: typeof AuthenticatedImportIndexRoute
  AuthenticatedIncidentsIndexRoute: typeof AuthenticatedIncidentsIndexRoute
  AuthenticatedLeaveIndexRoute: typeof AuthenticatedLeaveIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedOpsReadinessIndexRoute: typeof AuthenticatedOpsReadinessIndexRoute
  AuthenticatedProcurementIndexRoute: typeof AuthenticatedProcurementIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedRotaIndexRoute: typeof AuthenticatedRotaIndexRoute
  AuthenticatedServicesIndexRoute: typeof AuthenticatedServicesIndexRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
  AuthenticatedWorkIndexRoute: typeof AuthenticatedWorkIndexRoute
  AuthenticatedRotaCalendarIndexRoute: typeof AuthenticatedRotaCalendarIndexRoute
  AuthenticatedRotaFairnessIndexRoute: typeof AuthenticatedRotaFairnessIndexRoute
  AuthenticatedRotaWarningsIndexRoute: typeof AuthenticatedRotaWarningsIndexRoute
  AuthenticatedTimesheetsIndexRoute: typeof AuthenticatedTimesheetsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAccessAccountIdRoute: AuthenticatedAccessAccountIdRoute,
  AuthenticatedChangesChangeIdRoute: AuthenticatedChangesChangeIdRoute,
  AuthenticatedChangesNewRoute: AuthenticatedChangesNewRoute,
  AuthenticatedComplianceItemsRoute: AuthenticatedComplianceItemsRoute,
  AuthenticatedCompliancePpeRoute: AuthenticatedCompliancePpeRoute,
  AuthenticatedComplianceTrainingRoute: AuthenticatedComplianceTrainingRoute,
  AuthenticatedHrAttendanceRoute: AuthenticatedHrAttendanceRoute,
  AuthenticatedHrCalloutsRoute: AuthenticatedHrCalloutsRoute,
  AuthenticatedHrPpeRoute: AuthenticatedHrPpeRoute,
  AuthenticatedCyclesCycleIdRoute: AuthenticatedCyclesCycleIdRoute,
  AuthenticatedIncidentsIncidentIdRoute: AuthenticatedIncidentsIncidentIdRoute,
  AuthenticatedIncidentsNewRoute: AuthenticatedIncidentsNewRoute,
  AuthenticatedLeaveCalendarRoute: AuthenticatedLeaveCalendarRoute,
  AuthenticatedLeaveNewRoute: AuthenticatedLeaveNewRoute,
  AuthenticatedProcurementNewRoute: AuthenticatedProcurementNewRoute,
  AuthenticatedRotaHistoryRoute: AuthenticatedRotaHistoryRoute,
  AuthenticatedRotaPlannerRoute: AuthenticatedRotaPlannerRoute,
  AuthenticatedRotaSwapsRoute: AuthenticatedRotaSwapsRoute,
  AuthenticatedSettingsAutomationRoute: AuthenticatedSettingsAutomationRoute,
  AuthenticatedSettingsDepartmentsRoute: AuthenticatedSettingsDepartmentsRoute,
  AuthenticatedSettingsEscalationRoute: AuthenticatedSettingsEscalationRoute,
  AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
  AuthenticatedSettingsLeaveTypesRoute: AuthenticatedSettingsLeaveTypesRoute,
  AuthenticatedSettingsRolesRoute: AuthenticatedSettingsRolesRoute,
  AuthenticatedStaffStaffIdRoute: AuthenticatedStaffStaffIdRoute,
  AuthenticatedWorkWorkItemIdRoute: AuthenticatedWorkWorkItemIdRoute,
  AuthenticatedWorkNewRoute: AuthenticatedWorkNewRoute,
  AuthenticatedWorkWorkloadRoute: AuthenticatedWorkWorkloadRoute,
  AuthenticatedAccessIndexRoute: AuthenticatedAccessIndexRoute,
  AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  AuthenticatedAppraisalsIndexRoute: AuthenticatedAppraisalsIndexRoute,
  AuthenticatedAppraisalsInboxRoute: AuthenticatedAppraisalsInboxRoute,
  AuthenticatedAuditIndexRoute: AuthenticatedAuditIndexRoute,
  AuthenticatedChangesIndexRoute: AuthenticatedChangesIndexRoute,
  AuthenticatedContractsIndexRoute: AuthenticatedContractsIndexRoute,
  AuthenticatedCyclesIndexRoute: AuthenticatedCyclesIndexRoute,
  AuthenticatedImportIndexRoute: AuthenticatedImportIndexRoute,
  AuthenticatedIncidentsIndexRoute: AuthenticatedIncidentsIndexRoute,
  AuthenticatedLeaveIndexRoute: AuthenticatedLeaveIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedOpsReadinessIndexRoute: AuthenticatedOpsReadinessIndexRoute,
  AuthenticatedProcurementIndexRoute: AuthenticatedProcurementIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedRotaIndexRoute: AuthenticatedRotaIndexRoute,
  AuthenticatedServicesIndexRoute: AuthenticatedServicesIndexRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
  AuthenticatedWorkIndexRoute: AuthenticatedWorkIndexRoute,
  AuthenticatedRotaCalendarIndexRoute: AuthenticatedRotaCalendarIndexRoute,
  AuthenticatedRotaFairnessIndexRoute: AuthenticatedRotaFairnessIndexRoute,
  AuthenticatedRotaWarningsIndexRoute: AuthenticatedRotaWarningsIndexRoute,
  AuthenticatedTimesheetsIndexRoute: AuthenticatedTimesheetsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
